/**
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 *
 * Constraints:
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 */

fun main() {
    val s = "a"
    val t = "aa"

    val reuslt = Solution().findTheDifference(s, t)

    println(reuslt)
}

class Solution {
    // 시간 복잡도 : O(N)
    // 공간 복잡도 : O(1)
    fun findTheDifference(s: String, t: String): Char {
        var xor = 0

        for (c in s) {
            xor = xor xor c.code
        }

        for (c in t) {
            xor = xor xor c.code
        }

        return xor.toChar()
    }
}