name: Auto Merge

on:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Solved PRs
        id: get_prs
        run: |
          URL="https://api.github.com/repos/0chnxxx/Algorithm-Challenge/issues?state=open&labels=SOLVE"
          HEADERS=(
            "-H" "Accept: application/vnd.github+json"
            "-H" "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}"
            "-H" "X-GitHub-Api-Version: 2022-11-28"
          )
          RESPONSE=$(curl -s -L "${HEADERS[@]}" "$URL")
          echo "Response from API:"
          echo "$RESPONSE" | jq .
          echo "body=$(echo "$RESPONSE" | jq -c)" >> "$GITHUB_ENV"

      - name: Merge PRs
        if: steps.get-prs.outputs.body != '[]'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "Found Solved PRs:"
          echo ${{ steps.get-prs.outputs.body }}
          for pr in $(echo "${{ steps.get-prs.outputs.body }}" | jq -r '.[].number'); do
            echo "Merging PR #$pr"
            gh pr merge $pr --admin --merge
          done
