name: Auto Merge

on:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Solved PRs
        id: get_prs
        run: |
          url="https://api.github.com/repos/0chnxxx/Algorithm-Challenge/issues?state=open&labels=SOLVE"
          headers=(
            "-H" "Accept: application/vnd.github+json"
            "-H" "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}"
            "-H" "X-GitHub-Api-Version: 2022-11-28"
          )
          response=$(curl "${headers[@]}" "$url")
          echo "Response from API:"
          echo "$response" | jq .
          numbers=$(echo "$response" | jq -r '.[].number')
          echo "PR Numbers from Response:"
          echo "$numbers"
          echo "$numbers" >> "$GITHUB_ENV"

      - name: Merge PRs
        if: steps.get-prs.outputs.numbers != ''
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "Found Solved PR Numbers: ${{ steps.get_prs.outputs.numbers }}"
          for number in ${{ steps.get_prs.outputs.numbers }}; do
            url="https://api.github.com/repos/0chnxxx/Algorithm-Challenge/pulls/$number/merge"
            headers=(
              "-H" "Accept: application/vnd.github+json"
              "-H" "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}"
              "-H" "X-GitHub-Api-Version: 2022-11-28"
            )
            body='{"commit_title":"Auto Merge PR"}'
          
            curl -X PUT "${headers[@]}" -d "$body" "$url"
          done
