name: Update Readme

on:
  pull_request:
    types: [closed]

jobs:
  run-script:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run python script
        run: python script/collector.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md  # 변경된 파일 추가
          git commit -m "Update README.md"
          git push
        env:
          TOKEN: ${{ secrets.TOKEN }}
          OWNER: ${{ secrets.OWNER }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
